# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53f9cd1611ec3454657ad46f1238902f426d6bbb5fc4c1d8d1883152f15a1dd0f7e9498c7dda79d12d1d972f0180e093a4dabc0bf83075b6bf31f8c7add31f79

test:
  secret_key_base: 435929f748fc5367c56592e002314d121f7fb730e77c12939e7f3be5a2bd3a081ad646d7191c47087c892610af7c9608b05c22cf6989265732d73f88c0df0e44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
